Add env check to setup script
- only run `npm install` if PWD_RIVER_DISPATCHES_RELEASE env var unset
- replace tabs with spaces :art:

diff --git a/scripts/setup b/scripts/setup
--- a/scripts/setup
+++ b/scripts/setup
@@ -5,11 +5,13 @@ set -ex
 SOURCE_DIR=$1
 
 if [ -z "${SOURCE_DIR// }" ] || [ ! -d "$SOURCE_DIR" ] ; then
-	echo "Could not find source directory $SOURCE_DIR"
-	exit 1
+    echo "Could not find source directory $SOURCE_DIR"
+    exit 1
 fi
 
 cp -r "${SOURCE_DIR}"/images/* ./images/
 cp -r "${SOURCE_DIR}"/media/* ./media/
 
-npm install
+if [[ -z "${PWD_RIVER_DISPATCHES_RELEASE}" ]]; then
+    npm install
+fi
